export default {
    "objects":[
        {
            "type":"line",
            "originX":"center",
            "originY":"center",
            "left":98.41,
            "top":133.92,
            "width":5,
            "height":162,
            "fill":"black",
            "stroke":"black",
            "strokeWidth":2,
            "strokeDashArray":null,
            "strokeLineCap":"butt",
            "strokeLineJoin":"miter",
            "strokeMiterLimit":10,
            "scaleX":1,
            "scaleY":1,
            "angle":0,
            "flipX":false,
            "flipY":false,
            "opacity":1,
            "shadow":null,
            "visible":true,
            "clipTo":null,
            "backgroundColor":"",
            "fillRule":"nonzero",
            "globalCompositeOperation":"source-over",
            "transformMatrix":null,
            "skewX":0,
            "skewY":0,
            "x1":-2.5000111045611817,
            "x2":2.5000111045611817,
            "y1":-81.00166757284126,
            "y2":81.00166757284126
        },
        {
            "type":"line",
            "originX":"center",
            "originY":"center",
            "left":121.41,
            "top":130.42,
            "width":41,
            "height":1,
            "fill":"black",
            "stroke":"black",
            "strokeWidth":2,
            "strokeDashArray":null,
            "strokeLineCap":"butt",
            "strokeLineJoin":"miter",
            "strokeMiterLimit":10,
            "scaleX":1,
            "scaleY":1,
            "angle":0,
            "flipX":false,
            "flipY":false,
            "opacity":1,
            "shadow":null,
            "visible":true,
            "clipTo":null,
            "backgroundColor":"",
            "fillRule":"nonzero",
            "globalCompositeOperation":"source-over",
            "transformMatrix":null,
            "skewX":0,
            "skewY":0,
            "x1":-20.500091057401697,
            "x2":20.500091057401697,
            "y1":0.5000102936595141,
            "y2":-0.5000102936595141
        },
        {
            "type":"line",
            "originX":"center",
            "originY":"center",
            "left":144.41,
            "top":121.42,
            "width":1,
            "height":187,
            "fill":"black",
            "stroke":"black",
            "strokeWidth":2,
            "strokeDashArray":null,
            "strokeLineCap":"butt",
            "strokeLineJoin":"miter",
            "strokeMiterLimit":10,
            "scaleX":1,
            "scaleY":1,
            "angle":0,
            "flipX":false,
            "flipY":false,
            "opacity":1,
            "shadow":null,
            "visible":true,
            "clipTo":null,
            "backgroundColor":"",
            "fillRule":"nonzero",
            "globalCompositeOperation":"source-over",
            "transformMatrix":null,
            "skewX":0,
            "skewY":0,
            "x1":-0.5000022209122363,
            "x2":0.5000022209122363,
            "y1":-93.5019249143291,
            "y2":93.5019249143291
        },
        {
            "type":"line",
            "originX":"center",
            "originY":"center",
            "left":187.41,
            "top":182.92,
            "width":33,
            "height":0,
            "fill":"black",
            "stroke":"black",
            "strokeWidth":2,
            "strokeDashArray":null,
            "strokeLineCap":"butt",
            "strokeLineJoin":"miter",
            "strokeMiterLimit":10,
            "scaleX":1,
            "scaleY":1,
            "angle":0,
            "flipX":false,
            "flipY":false,
            "opacity":1,
            "shadow":null,
            "visible":true,
            "clipTo":null,
            "backgroundColor":"",
            "fillRule":"nonzero",
            "globalCompositeOperation":"source-over",
            "transformMatrix":null,
            "skewX":0,
            "skewY":0,
            "x1":-16.5000732901038,
            "x2":16.5000732901038,
            "y1":0,
            "y2":0
        },
        {
            "type":"line",
            "originX":"center",
            "originY":"center",
            "left":202.41,
            "top":166.42,
            "width":3,
            "height":33,
            "fill":"black",
            "stroke":"black",
            "strokeWidth":2,
            "strokeDashArray":null,
            "strokeLineCap":"butt",
            "strokeLineJoin":"miter",
            "strokeMiterLimit":10,
            "scaleX":1,
            "scaleY":1,
            "angle":0,
            "flipX":false,
            "flipY":false,
            "opacity":1,
            "shadow":null,
            "visible":true,
            "clipTo":null,
            "backgroundColor":"",
            "fillRule":"nonzero",
            "globalCompositeOperation":"source-over",
            "transformMatrix":null,
            "skewX":0,
            "skewY":0,
            "x1":1.500006662736709,
            "x2":-1.500006662736709,
            "y1":16.500339690763965,
            "y2":-16.500339690763965
        },
        {
            "type":"line",
            "originX":"center",
            "originY":"center",
            "left":184.41,
            "top":149.92,
            "width":35,
            "height":0,
            "fill":"black",
            "stroke":"black",
            "strokeWidth":2,
            "strokeDashArray":null,
            "strokeLineCap":"butt",
            "strokeLineJoin":"miter",
            "strokeMiterLimit":10,
            "scaleX":1,
            "scaleY":1,
            "angle":0,
            "flipX":false,
            "flipY":false,
            "opacity":1,
            "shadow":null,
            "visible":true,
            "clipTo":null,
            "backgroundColor":"",
            "fillRule":"nonzero",
            "globalCompositeOperation":"source-over",
            "transformMatrix":null,
            "skewX":0,
            "skewY":0,
            "x1":17.500077731928272,
            "x2":-17.500077731928272,
            "y1":0,
            "y2":0
        },
        {
            "type":"line",
            "originX":"center",
            "originY":"center",
            "left":169.91,
            "top":182.42,
            "width":6,
            "height":65,
            "fill":"black",
            "stroke":"black",
            "strokeWidth":2,
            "strokeDashArray":null,
            "strokeLineCap":"butt",
            "strokeLineJoin":"miter",
            "strokeMiterLimit":10,
            "scaleX":1,
            "scaleY":1,
            "angle":0,
            "flipX":false,
            "flipY":false,
            "opacity":1,
            "shadow":null,
            "visible":true,
            "clipTo":null,
            "backgroundColor":"",
            "fillRule":"nonzero",
            "globalCompositeOperation":"source-over",
            "transformMatrix":null,
            "skewX":0,
            "skewY":0,
            "x1":-3.000013325473418,
            "x2":3.000013325473418,
            "y1":-32.5006690878684,
            "y2":32.5006690878684
        },
        {
            "type":"line",
            "originX":"center",
            "originY":"center",
            "left":189.91,
            "top":215.42,
            "width":34,
            "height":1,
            "fill":"black",
            "stroke":"black",
            "strokeWidth":2,
            "strokeDashArray":null,
            "strokeLineCap":"butt",
            "strokeLineJoin":"miter",
            "strokeMiterLimit":10,
            "scaleX":1,
            "scaleY":1,
            "angle":0,
            "flipX":false,
            "flipY":false,
            "opacity":1,
            "shadow":null,
            "visible":true,
            "clipTo":null,
            "backgroundColor":"",
            "fillRule":"nonzero",
            "globalCompositeOperation":"source-over",
            "transformMatrix":null,
            "skewX":0,
            "skewY":0,
            "x1":-17.000075511016036,
            "x2":17.000075511016036,
            "y1":-0.5000102936595141,
            "y2":0.5000102936595141
        },
        {
            "type":"line",
            "originX":"center",
            "originY":"center",
            "left":235.91,
            "top":134.92,
            "width":10,
            "height":156,
            "fill":"black",
            "stroke":"black",
            "strokeWidth":2,
            "strokeDashArray":null,
            "strokeLineCap":"butt",
            "strokeLineJoin":"miter",
            "strokeMiterLimit":10,
            "scaleX":1,
            "scaleY":1,
            "angle":0,
            "flipX":false,
            "flipY":false,
            "opacity":1,
            "shadow":null,
            "visible":true,
            "clipTo":null,
            "backgroundColor":"",
            "fillRule":"nonzero",
            "globalCompositeOperation":"source-over",
            "transformMatrix":null,
            "skewX":0,
            "skewY":0,
            "x1":5.000022209122363,
            "x2":-5.000022209122363,
            "y1":78.00160581088417,
            "y2":-78.00160581088417
        },
        {
            "type":"line",
            "originX":"center",
            "originY":"center",
            "left":260.91,
            "top":135.92,
            "width":12,
            "height":148,
            "fill":"black",
            "stroke":"black",
            "strokeWidth":2,
            "strokeDashArray":null,
            "strokeLineCap":"butt",
            "strokeLineJoin":"miter",
            "strokeMiterLimit":10,
            "scaleX":1,
            "scaleY":1,
            "angle":0,
            "flipX":false,
            "flipY":false,
            "opacity":1,
            "shadow":null,
            "visible":true,
            "clipTo":null,
            "backgroundColor":"",
            "fillRule":"nonzero",
            "globalCompositeOperation":"source-over",
            "transformMatrix":null,
            "skewX":0,
            "skewY":0,
            "x1":6.00002665094685,
            "x2":-6.00002665094685,
            "y1":74.00152346160806,
            "y2":-74.00152346160806
        },
        {
            "type":"circle",
            "originX":"left",
            "originY":"center",
            "left":284.91,
            "top":154.92,
            "width":57.32,
            "height":57.32,
            "fill":"transparent",
            "stroke":"black",
            "strokeWidth":2,
            "strokeDashArray":null,
            "strokeLineCap":"butt",
            "strokeLineJoin":"miter",
            "strokeMiterLimit":10,
            "scaleX":1,
            "scaleY":1,
            "angle":47.12,
            "flipX":false,
            "flipY":false,
            "opacity":1,
            "shadow":null,
            "visible":true,
            "clipTo":null,
            "backgroundColor":"",
            "fillRule":"nonzero",
            "globalCompositeOperation":"source-over",
            "transformMatrix":null,
            "skewX":0,
            "skewY":0,
            "radius":28.65783551172888,
            "startAngle":0,
            "endAngle":6.283185307179586
        },
        {
            "type":"rect",
            "originX":"left",
            "originY":"top",
            "left":374.91,
            "top":46.91,
            "width":14,
            "height":123,
            "fill":"#b0bc00",
            "stroke":"black",
            "strokeWidth":2,
            "strokeDashArray":null,
            "strokeLineCap":"butt",
            "strokeLineJoin":"miter",
            "strokeMiterLimit":10,
            "scaleX":1,
            "scaleY":1,
            "angle":0,
            "flipX":false,
            "flipY":false,
            "opacity":1,
            "shadow":null,
            "visible":true,
            "clipTo":null,
            "backgroundColor":"",
            "fillRule":"nonzero",
            "globalCompositeOperation":"source-over",
            "transformMatrix":null,
            "skewX":0,
            "skewY":0,
            "rx":0,
            "ry":0
        },
        {
            "type":"circle",
            "originX":"left",
            "originY":"center",
            "left":373.91,
            "top":182.92,
            "width":21.93,
            "height":21.93,
            "fill":"#b0bc00",
            "stroke":"black",
            "strokeWidth":2,
            "strokeDashArray":null,
            "strokeLineCap":"butt",
            "strokeLineJoin":"miter",
            "strokeMiterLimit":10,
            "scaleX":1,
            "scaleY":1,
            "angle":46.85,
            "flipX":false,
            "flipY":false,
            "opacity":1,
            "shadow":null,
            "visible":true,
            "clipTo":null,
            "backgroundColor":"",
            "fillRule":"nonzero",
            "globalCompositeOperation":"source-over",
            "transformMatrix":null,
            "skewX":0,
            "skewY":0,
            "radius":10.96599903840613,
            "startAngle":0,
            "endAngle":6.283185307179586
        },
        {
            "type":"path",
            "originX":"left",
            "originY":"top",
            "left":664,
            "top":82.99000000000001,
            "width":8.01,
            "height":126.02,
            "fill":null,
            "stroke":"black",
            "strokeWidth":10,
            "strokeDashArray":null,
            "strokeLineCap":"round",
            "strokeLineJoin":"round",
            "strokeMiterLimit":10,
            "scaleX":1,
            "scaleY":1,
            "angle":0,
            "flipX":false,
            "flipY":false,
            "opacity":1,
            "shadow":null,
            "visible":true,
            "clipTo":null,
            "backgroundColor":"",
            "fillRule":"nonzero",
            "globalCompositeOperation":"source-over",
            "transformMatrix":null,
            "skewX":0,
            "skewY":0,
            "pathOffset":{
                "x":673.005,
                "y":151
            },
            "path":[
                [
                    "M",
                    669,
                    87.99
                ],
                [
                    "Q",
                    669,
                    88,
                    669,
                    88.5
                ],
                [
                    "Q",
                    669,
                    89,
                    669,
                    90.5
                ],
                [
                    "Q",
                    669,
                    92,
                    669,
                    96
                ],
                [
                    "Q",
                    669,
                    100,
                    669,
                    107.5
                ],
                [
                    "Q",
                    669,
                    115,
                    669,
                    119
                ],
                [
                    "Q",
                    669,
                    123,
                    669,
                    125.5
                ],
                [
                    "Q",
                    669,
                    128,
                    669,
                    132.5
                ],
                [
                    "Q",
                    669,
                    137,
                    669,
                    140
                ],
                [
                    "Q",
                    669,
                    143,
                    669,
                    149
                ],
                [
                    "Q",
                    669,
                    155,
                    669,
                    160.5
                ],
                [
                    "Q",
                    669,
                    166,
                    669,
                    172.5
                ],
                [
                    "Q",
                    669,
                    179,
                    669.5,
                    183
                ],
                [
                    "Q",
                    670,
                    187,
                    670.5,
                    191
                ],
                [
                    "Q",
                    671,
                    195,
                    671,
                    198
                ],
                [
                    "Q",
                    671,
                    201,
                    671.5,
                    203
                ],
                [
                    "Q",
                    672,
                    205,
                    672,
                    206.5
                ],
                [
                    "Q",
                    672,
                    208,
                    672.5,
                    209
                ],
                [
                    "Q",
                    673,
                    210,
                    673.5,
                    211
                ],
                [
                    "Q",
                    674,
                    212,
                    674.5,
                    212.5
                ],
                [
                    "Q",
                    675,
                    213,
                    676,
                    213.5
                ],
                [
                    "L",
                    677.01,
                    214.01
                ]
            ]
        },
        {
            "type":"path",
            "originX":"left",
            "originY":"top",
            "left":605.99,
            "top":76,
            "width":133.02,
            "height":9.01,
            "fill":null,
            "stroke":"black",
            "strokeWidth":10,
            "strokeDashArray":null,
            "strokeLineCap":"round",
            "strokeLineJoin":"round",
            "strokeMiterLimit":10,
            "scaleX":1,
            "scaleY":1,
            "angle":0,
            "flipX":false,
            "flipY":false,
            "opacity":1,
            "shadow":null,
            "visible":true,
            "clipTo":null,
            "backgroundColor":"",
            "fillRule":"nonzero",
            "globalCompositeOperation":"source-over",
            "transformMatrix":null,
            "skewX":0,
            "skewY":0,
            "pathOffset":{
                "x":677.5,
                "y":85.505
            },
            "path":[
                [
                    "M",
                    610.99,
                    81
                ],
                [
                    "Q",
                    611,
                    81,
                    611.5,
                    81
                ],
                [
                    "Q",
                    612,
                    81,
                    612.5,
                    81
                ],
                [
                    "Q",
                    613,
                    81,
                    614.5,
                    81
                ],
                [
                    "Q",
                    616,
                    81,
                    621,
                    81
                ],
                [
                    "Q",
                    626,
                    81,
                    632.5,
                    81
                ],
                [
                    "Q",
                    639,
                    81,
                    646,
                    81
                ],
                [
                    "Q",
                    653,
                    81,
                    659,
                    81
                ],
                [
                    "Q",
                    665,
                    81,
                    670.5,
                    81
                ],
                [
                    "Q",
                    676,
                    81,
                    680,
                    81
                ],
                [
                    "Q",
                    684,
                    81,
                    688,
                    81
                ],
                [
                    "Q",
                    692,
                    81,
                    695,
                    81
                ],
                [
                    "Q",
                    698,
                    81,
                    701.5,
                    81
                ],
                [
                    "Q",
                    705,
                    81,
                    708.5,
                    81.5
                ],
                [
                    "Q",
                    712,
                    82,
                    715,
                    82.5
                ],
                [
                    "Q",
                    718,
                    83,
                    719.5,
                    83.5
                ],
                [
                    "Q",
                    721,
                    84,
                    723.5,
                    84.5
                ],
                [
                    "Q",
                    726,
                    85,
                    727.5,
                    85.5
                ],
                [
                    "Q",
                    729,
                    86,
                    730.5,
                    86
                ],
                [
                    "Q",
                    732,
                    86,
                    735,
                    87
                ],
                [
                    "Q",
                    738,
                    88,
                    741,
                    89
                ],
                [
                    "L",
                    744.01,
                    90.01
                ]
            ]
        },
        {
            "type":"path",
            "originX":"left",
            "originY":"top",
            "left":801,
            "top":73,
            "width":123,
            "height":111,
            "fill":null,
            "stroke":"black",
            "strokeWidth":10,
            "strokeDashArray":null,
            "strokeLineCap":"round",
            "strokeLineJoin":"round",
            "strokeMiterLimit":10,
            "scaleX":1,
            "scaleY":1,
            "angle":0,
            "flipX":false,
            "flipY":false,
            "opacity":1,
            "shadow":null,
            "visible":true,
            "clipTo":null,
            "backgroundColor":"",
            "fillRule":"nonzero",
            "globalCompositeOperation":"source-over",
            "transformMatrix":null,
            "skewX":0,
            "skewY":0,
            "pathOffset":{
                "x":867.5,
                "y":133.5
            },
            "path":[
                [
                    "M",
                    806,
                    78.99
                ],
                [
                    "Q",
                    806,
                    79,
                    806,
                    80.5
                ],
                [
                    "Q",
                    806,
                    82,
                    806,
                    84.5
                ],
                [
                    "Q",
                    806,
                    87,
                    806,
                    91
                ],
                [
                    "Q",
                    806,
                    95,
                    806,
                    101
                ],
                [
                    "Q",
                    806,
                    107,
                    806,
                    113
                ],
                [
                    "Q",
                    806,
                    119,
                    806,
                    124
                ],
                [
                    "Q",
                    806,
                    129,
                    806.5,
                    132.5
                ],
                [
                    "Q",
                    807,
                    136,
                    807.5,
                    141.5
                ],
                [
                    "Q",
                    808,
                    147,
                    809,
                    150.5
                ],
                [
                    "Q",
                    810,
                    154,
                    811,
                    157.5
                ],
                [
                    "Q",
                    812,
                    161,
                    813,
                    162.5
                ],
                [
                    "Q",
                    814,
                    164,
                    815,
                    166.5
                ],
                [
                    "Q",
                    816,
                    169,
                    817,
                    171
                ],
                [
                    "Q",
                    818,
                    173,
                    819.5,
                    174.5
                ],
                [
                    "Q",
                    821,
                    176,
                    822.5,
                    177.5
                ],
                [
                    "Q",
                    824,
                    179,
                    826,
                    180
                ],
                [
                    "Q",
                    828,
                    181,
                    829.5,
                    181.5
                ],
                [
                    "Q",
                    831,
                    182,
                    833.5,
                    183
                ],
                [
                    "Q",
                    836,
                    184,
                    838,
                    185
                ],
                [
                    "Q",
                    840,
                    186,
                    843,
                    186.5
                ],
                [
                    "Q",
                    846,
                    187,
                    849,
                    187.5
                ],
                [
                    "Q",
                    852,
                    188,
                    855.5,
                    188.5
                ],
                [
                    "Q",
                    859,
                    189,
                    862,
                    189
                ],
                [
                    "Q",
                    865,
                    189,
                    868,
                    189
                ],
                [
                    "Q",
                    871,
                    189,
                    874,
                    187.5
                ],
                [
                    "Q",
                    877,
                    186,
                    882.5,
                    183
                ],
                [
                    "Q",
                    888,
                    180,
                    889.5,
                    178.5
                ],
                [
                    "Q",
                    891,
                    177,
                    896,
                    173.5
                ],
                [
                    "Q",
                    901,
                    170,
                    904,
                    166.5
                ],
                [
                    "Q",
                    907,
                    163,
                    910,
                    158.5
                ],
                [
                    "Q",
                    913,
                    154,
                    916,
                    149
                ],
                [
                    "Q",
                    919,
                    144,
                    921.5,
                    137.5
                ],
                [
                    "Q",
                    924,
                    131,
                    925.5,
                    124.5
                ],
                [
                    "Q",
                    927,
                    118,
                    928,
                    111.5
                ],
                [
                    "Q",
                    929,
                    105,
                    929,
                    101.5
                ],
                [
                    "Q",
                    929,
                    98,
                    929,
                    94
                ],
                [
                    "Q",
                    929,
                    90,
                    929,
                    88
                ],
                [
                    "Q",
                    929,
                    86,
                    929,
                    84.5
                ],
                [
                    "Q",
                    929,
                    83,
                    929,
                    82
                ],
                [
                    "Q",
                    929,
                    81,
                    928.5,
                    80.5
                ],
                [
                    "Q",
                    928,
                    80,
                    928,
                    79.5
                ],
                [
                    "Q",
                    928,
                    79,
                    927.5,
                    79
                ],
                [
                    "Q",
                    927,
                    79,
                    926.5,
                    78.5
                ],
                [
                    "Q",
                    926,
                    78,
                    925.5,
                    78
                ],
                [
                    "L",
                    924.99,
                    78
                ]
            ]
        },
        {
            "type":"path",
            "originX":"left",
            "originY":"top",
            "left":554,
            "top":297.99,
            "width":10,
            "height":111.02,
            "fill":null,
            "stroke":"black",
            "strokeWidth":10,
            "strokeDashArray":null,
            "strokeLineCap":"round",
            "strokeLineJoin":"round",
            "strokeMiterLimit":10,
            "scaleX":1,
            "scaleY":1,
            "angle":0,
            "flipX":false,
            "flipY":false,
            "opacity":1,
            "shadow":null,
            "visible":true,
            "clipTo":null,
            "backgroundColor":"",
            "fillRule":"nonzero",
            "globalCompositeOperation":"source-over",
            "transformMatrix":null,
            "skewX":0,
            "skewY":0,
            "pathOffset":{
                "x":564,
                "y":358.5
            },
            "path":[
                [
                    "M",
                    559,
                    302.99
                ],
                [
                    "Q",
                    559,
                    303,
                    559,
                    305
                ],
                [
                    "Q",
                    559,
                    307,
                    559.5,
                    311.5
                ],
                [
                    "Q",
                    560,
                    316,
                    560.5,
                    322.5
                ],
                [
                    "Q",
                    561,
                    329,
                    561.5,
                    335
                ],
                [
                    "Q",
                    562,
                    341,
                    562.5,
                    347
                ],
                [
                    "Q",
                    563,
                    353,
                    563.5,
                    359
                ],
                [
                    "Q",
                    564,
                    365,
                    564.5,
                    370.5
                ],
                [
                    "Q",
                    565,
                    376,
                    565.5,
                    380
                ],
                [
                    "Q",
                    566,
                    384,
                    566.5,
                    388.5
                ],
                [
                    "Q",
                    567,
                    393,
                    567,
                    396
                ],
                [
                    "Q",
                    567,
                    399,
                    567.5,
                    401
                ],
                [
                    "Q",
                    568,
                    403,
                    568,
                    404.5
                ],
                [
                    "Q",
                    568,
                    406,
                    568.5,
                    407
                ],
                [
                    "Q",
                    569,
                    408,
                    569,
                    409
                ],
                [
                    "Q",
                    569,
                    410,
                    569,
                    411.5
                ],
                [
                    "Q",
                    569,
                    413,
                    569,
                    413.5
                ],
                [
                    "L",
                    569,
                    414.01
                ]
            ]
        },
        {
            "type":"path",
            "originX":"left",
            "originY":"top",
            "left":523,
            "top":297,
            "width":111,
            "height":57,
            "fill":null,
            "stroke":"black",
            "strokeWidth":10,
            "strokeDashArray":null,
            "strokeLineCap":"round",
            "strokeLineJoin":"round",
            "strokeMiterLimit":10,
            "scaleX":1,
            "scaleY":1,
            "angle":0,
            "flipX":false,
            "flipY":false,
            "opacity":1,
            "shadow":null,
            "visible":true,
            "clipTo":null,
            "backgroundColor":"",
            "fillRule":"nonzero",
            "globalCompositeOperation":"source-over",
            "transformMatrix":null,
            "skewX":0,
            "skewY":0,
            "pathOffset":{
                "x":583.5,
                "y":330.5
            },
            "path":[
                [
                    "M",
                    528,
                    335.01
                ],
                [
                    "Q",
                    528,
                    335,
                    528,
                    334.5
                ],
                [
                    "Q",
                    528,
                    334,
                    528.5,
                    334
                ],
                [
                    "Q",
                    529,
                    334,
                    531,
                    332.5
                ],
                [
                    "Q",
                    533,
                    331,
                    536,
                    329.5
                ],
                [
                    "Q",
                    539,
                    328,
                    542.5,
                    326.5
                ],
                [
                    "Q",
                    546,
                    325,
                    550,
                    323
                ],
                [
                    "Q",
                    554,
                    321,
                    559,
                    318.5
                ],
                [
                    "Q",
                    564,
                    316,
                    569,
                    314
                ],
                [
                    "Q",
                    574,
                    312,
                    578.5,
                    310.5
                ],
                [
                    "Q",
                    583,
                    309,
                    587,
                    307.5
                ],
                [
                    "Q",
                    591,
                    306,
                    593.5,
                    305.5
                ],
                [
                    "Q",
                    596,
                    305,
                    599,
                    304
                ],
                [
                    "Q",
                    602,
                    303,
                    604.5,
                    302.5
                ],
                [
                    "Q",
                    607,
                    302,
                    609.5,
                    302
                ],
                [
                    "Q",
                    612,
                    302,
                    614,
                    302
                ],
                [
                    "Q",
                    616,
                    302,
                    619,
                    302.5
                ],
                [
                    "Q",
                    622,
                    303,
                    624,
                    304
                ],
                [
                    "Q",
                    626,
                    305,
                    627.5,
                    306
                ],
                [
                    "Q",
                    629,
                    307,
                    630.5,
                    308
                ],
                [
                    "Q",
                    632,
                    309,
                    633.5,
                    310.5
                ],
                [
                    "Q",
                    635,
                    312,
                    635.5,
                    313.5
                ],
                [
                    "Q",
                    636,
                    315,
                    637,
                    316.5
                ],
                [
                    "Q",
                    638,
                    318,
                    638.5,
                    319.5
                ],
                [
                    "Q",
                    639,
                    321,
                    639,
                    322
                ],
                [
                    "Q",
                    639,
                    323,
                    639,
                    324.5
                ],
                [
                    "Q",
                    639,
                    326,
                    639,
                    327
                ],
                [
                    "Q",
                    639,
                    328,
                    639,
                    328.5
                ],
                [
                    "Q",
                    639,
                    329,
                    638.5,
                    330
                ],
                [
                    "Q",
                    638,
                    331,
                    637.5,
                    332
                ],
                [
                    "Q",
                    637,
                    333,
                    636,
                    334
                ],
                [
                    "Q",
                    635,
                    335,
                    634,
                    336.5
                ],
                [
                    "Q",
                    633,
                    338,
                    632,
                    339
                ],
                [
                    "Q",
                    631,
                    340,
                    630,
                    341
                ],
                [
                    "Q",
                    629,
                    342,
                    628,
                    343
                ],
                [
                    "Q",
                    627,
                    344,
                    625,
                    345.5
                ],
                [
                    "Q",
                    623,
                    347,
                    621,
                    348
                ],
                [
                    "Q",
                    619,
                    349,
                    617.5,
                    349.5
                ],
                [
                    "Q",
                    616,
                    350,
                    614,
                    351
                ],
                [
                    "Q",
                    612,
                    352,
                    610.5,
                    352.5
                ],
                [
                    "Q",
                    609,
                    353,
                    607.5,
                    353.5
                ],
                [
                    "Q",
                    606,
                    354,
                    603.5,
                    354.5
                ],
                [
                    "Q",
                    601,
                    355,
                    599,
                    355.5
                ],
                [
                    "Q",
                    597,
                    356,
                    595,
                    356.5
                ],
                [
                    "Q",
                    593,
                    357,
                    591,
                    357.5
                ],
                [
                    "Q",
                    589,
                    358,
                    587.5,
                    358
                ],
                [
                    "Q",
                    586,
                    358,
                    585,
                    358.5
                ],
                [
                    "Q",
                    584,
                    359,
                    583.5,
                    359
                ],
                [
                    "Q",
                    583,
                    359,
                    582.5,
                    359
                ],
                [
                    "Q",
                    582,
                    359,
                    581.5,
                    359
                ],
                [
                    "Q",
                    581,
                    359,
                    580.5,
                    359
                ],
                [
                    "Q",
                    580,
                    359,
                    579.5,
                    359
                ],
                [
                    "Q",
                    579,
                    359,
                    578.5,
                    359
                ],
                [
                    "L",
                    577.99,
                    359
                ]
            ]
        },
        {
            "type":"path",
            "originX":"left",
            "originY":"top",
            "left":698,
            "top":298.99,
            "width":71,
            "height":55.01,
            "fill":null,
            "stroke":"black",
            "strokeWidth":10,
            "strokeDashArray":null,
            "strokeLineCap":"round",
            "strokeLineJoin":"round",
            "strokeMiterLimit":10,
            "scaleX":1,
            "scaleY":1,
            "angle":0,
            "flipX":false,
            "flipY":false,
            "opacity":1,
            "shadow":null,
            "visible":true,
            "clipTo":null,
            "backgroundColor":"",
            "fillRule":"nonzero",
            "globalCompositeOperation":"source-over",
            "transformMatrix":null,
            "skewX":0,
            "skewY":0,
            "pathOffset":{
                "x":738.5,
                "y":331.495
            },
            "path":[
                [
                    "M",
                    703,
                    303.99
                ],
                [
                    "Q",
                    703,
                    304,
                    703,
                    304.5
                ],
                [
                    "Q",
                    703,
                    305,
                    703,
                    305.5
                ],
                [
                    "Q",
                    703,
                    306,
                    703,
                    308.5
                ],
                [
                    "Q",
                    703,
                    311,
                    703,
                    316
                ],
                [
                    "Q",
                    703,
                    321,
                    703.5,
                    324.5
                ],
                [
                    "Q",
                    704,
                    328,
                    704.5,
                    330.5
                ],
                [
                    "Q",
                    705,
                    333,
                    705.5,
                    335
                ],
                [
                    "Q",
                    706,
                    337,
                    706.5,
                    339
                ],
                [
                    "Q",
                    707,
                    341,
                    708,
                    342.5
                ],
                [
                    "Q",
                    709,
                    344,
                    709.5,
                    345.5
                ],
                [
                    "Q",
                    710,
                    347,
                    710.5,
                    348
                ],
                [
                    "Q",
                    711,
                    349,
                    712,
                    350
                ],
                [
                    "Q",
                    713,
                    351,
                    713.5,
                    352
                ],
                [
                    "Q",
                    714,
                    353,
                    715,
                    354
                ],
                [
                    "Q",
                    716,
                    355,
                    717.5,
                    355.5
                ],
                [
                    "Q",
                    719,
                    356,
                    720.5,
                    357
                ],
                [
                    "Q",
                    722,
                    358,
                    724,
                    358.5
                ],
                [
                    "Q",
                    726,
                    359,
                    728,
                    359
                ],
                [
                    "Q",
                    730,
                    359,
                    732.5,
                    359
                ],
                [
                    "Q",
                    735,
                    359,
                    737,
                    359
                ],
                [
                    "Q",
                    739,
                    359,
                    740.5,
                    359
                ],
                [
                    "Q",
                    742,
                    359,
                    743.5,
                    359
                ],
                [
                    "Q",
                    745,
                    359,
                    746.5,
                    358.5
                ],
                [
                    "Q",
                    748,
                    358,
                    749.5,
                    357
                ],
                [
                    "Q",
                    751,
                    356,
                    753.5,
                    354.5
                ],
                [
                    "Q",
                    756,
                    353,
                    757,
                    352.5
                ],
                [
                    "Q",
                    758,
                    352,
                    760,
                    350.5
                ],
                [
                    "Q",
                    762,
                    349,
                    764,
                    348
                ],
                [
                    "Q",
                    766,
                    347,
                    767,
                    345.5
                ],
                [
                    "Q",
                    768,
                    344,
                    769,
                    343
                ],
                [
                    "Q",
                    770,
                    342,
                    771,
                    340.5
                ],
                [
                    "Q",
                    772,
                    339,
                    772.5,
                    338
                ],
                [
                    "Q",
                    773,
                    337,
                    773,
                    336
                ],
                [
                    "Q",
                    773,
                    335,
                    773.5,
                    333.5
                ],
                [
                    "Q",
                    774,
                    332,
                    774,
                    330.5
                ],
                [
                    "Q",
                    774,
                    329,
                    774,
                    327.5
                ],
                [
                    "Q",
                    774,
                    326,
                    774,
                    324.5
                ],
                [
                    "Q",
                    774,
                    323,
                    773.5,
                    321.5
                ],
                [
                    "Q",
                    773,
                    320,
                    772.5,
                    319
                ],
                [
                    "Q",
                    772,
                    318,
                    771,
                    316.5
                ],
                [
                    "Q",
                    770,
                    315,
                    769.5,
                    314
                ],
                [
                    "Q",
                    769,
                    313,
                    768,
                    311
                ],
                [
                    "Q",
                    767,
                    309,
                    766.5,
                    308.5
                ],
                [
                    "Q",
                    766,
                    308,
                    766,
                    307.5
                ],
                [
                    "Q",
                    766,
                    307,
                    765.5,
                    306.5
                ],
                [
                    "Q",
                    765,
                    306,
                    764.5,
                    305.5
                ],
                [
                    "L",
                    763.99,
                    304.99
                ]
            ]
        },
        {
            "type":"path",
            "originX":"left",
            "originY":"top",
            "left":782,
            "top":293,
            "width":71.01,
            "height":66,
            "fill":null,
            "stroke":"black",
            "strokeWidth":10,
            "strokeDashArray":null,
            "strokeLineCap":"round",
            "strokeLineJoin":"round",
            "strokeMiterLimit":10,
            "scaleX":1,
            "scaleY":1,
            "angle":0,
            "flipX":false,
            "flipY":false,
            "opacity":1,
            "shadow":null,
            "visible":true,
            "clipTo":null,
            "backgroundColor":"",
            "fillRule":"nonzero",
            "globalCompositeOperation":"source-over",
            "transformMatrix":null,
            "skewX":0,
            "skewY":0,
            "pathOffset":{
                "x":822.505,
                "y":331
            },
            "path":[
                [
                    "M",
                    852.01,
                    298
                ],
                [
                    "Q",
                    852,
                    298,
                    851,
                    298
                ],
                [
                    "Q",
                    850,
                    298,
                    849.5,
                    298
                ],
                [
                    "Q",
                    849,
                    298,
                    845.5,
                    298
                ],
                [
                    "Q",
                    842,
                    298,
                    839.5,
                    298
                ],
                [
                    "Q",
                    837,
                    298,
                    833,
                    298
                ],
                [
                    "Q",
                    829,
                    298,
                    827,
                    298
                ],
                [
                    "Q",
                    825,
                    298,
                    822,
                    298
                ],
                [
                    "Q",
                    819,
                    298,
                    816,
                    298.5
                ],
                [
                    "Q",
                    813,
                    299,
                    811,
                    299.5
                ],
                [
                    "Q",
                    809,
                    300,
                    807,
                    300.5
                ],
                [
                    "Q",
                    805,
                    301,
                    803,
                    302.5
                ],
                [
                    "Q",
                    801,
                    304,
                    799,
                    304.5
                ],
                [
                    "Q",
                    797,
                    305,
                    795,
                    306.5
                ],
                [
                    "Q",
                    793,
                    308,
                    792,
                    308.5
                ],
                [
                    "Q",
                    791,
                    309,
                    790,
                    309.5
                ],
                [
                    "Q",
                    789,
                    310,
                    788.5,
                    310.5
                ],
                [
                    "Q",
                    788,
                    311,
                    787.5,
                    311
                ],
                [
                    "Q",
                    787,
                    311,
                    787,
                    311.5
                ],
                [
                    "Q",
                    787,
                    312,
                    787.5,
                    312.5
                ],
                [
                    "Q",
                    788,
                    313,
                    788.5,
                    313.5
                ],
                [
                    "Q",
                    789,
                    314,
                    789.5,
                    314.5
                ],
                [
                    "Q",
                    790,
                    315,
                    790,
                    315.5
                ],
                [
                    "Q",
                    790,
                    316,
                    791,
                    317
                ],
                [
                    "Q",
                    792,
                    318,
                    793,
                    322.5
                ],
                [
                    "Q",
                    794,
                    327,
                    794.5,
                    328.5
                ],
                [
                    "Q",
                    795,
                    330,
                    796,
                    334
                ],
                [
                    "Q",
                    797,
                    338,
                    797.5,
                    340
                ],
                [
                    "Q",
                    798,
                    342,
                    798.5,
                    344
                ],
                [
                    "Q",
                    799,
                    346,
                    799,
                    347
                ],
                [
                    "Q",
                    799,
                    348,
                    799.5,
                    349
                ],
                [
                    "Q",
                    800,
                    350,
                    800,
                    351
                ],
                [
                    "Q",
                    800,
                    352,
                    800.5,
                    353
                ],
                [
                    "Q",
                    801,
                    354,
                    801,
                    355
                ],
                [
                    "Q",
                    801,
                    356,
                    801,
                    357
                ],
                [
                    "Q",
                    801,
                    358,
                    801.5,
                    358.5
                ],
                [
                    "Q",
                    802,
                    359,
                    802,
                    360
                ],
                [
                    "Q",
                    802,
                    361,
                    802,
                    361.5
                ],
                [
                    "Q",
                    802,
                    362,
                    802,
                    362.5
                ],
                [
                    "Q",
                    802,
                    363,
                    802.5,
                    363.5
                ],
                [
                    "Q",
                    803,
                    364,
                    803.5,
                    364
                ],
                [
                    "Q",
                    804,
                    364,
                    804.5,
                    364
                ],
                [
                    "Q",
                    805,
                    364,
                    806,
                    364
                ],
                [
                    "Q",
                    807,
                    364,
                    808,
                    364
                ],
                [
                    "Q",
                    809,
                    364,
                    811,
                    364
                ],
                [
                    "Q",
                    813,
                    364,
                    815,
                    364
                ],
                [
                    "Q",
                    817,
                    364,
                    819.5,
                    364
                ],
                [
                    "Q",
                    822,
                    364,
                    825,
                    364
                ],
                [
                    "Q",
                    828,
                    364,
                    830.5,
                    364
                ],
                [
                    "Q",
                    833,
                    364,
                    835,
                    363.5
                ],
                [
                    "Q",
                    837,
                    363,
                    840,
                    362.5
                ],
                [
                    "Q",
                    843,
                    362,
                    845,
                    361.5
                ],
                [
                    "Q",
                    847,
                    361,
                    849,
                    361
                ],
                [
                    "Q",
                    851,
                    361,
                    852.5,
                    360.5
                ],
                [
                    "Q",
                    854,
                    360,
                    855,
                    359.5
                ],
                [
                    "Q",
                    856,
                    359,
                    856.5,
                    359
                ],
                [
                    "Q",
                    857,
                    359,
                    857.5,
                    358.5
                ],
                [
                    "L",
                    858.01,
                    357.99
                ]
            ]
        },
        {
            "type":"path",
            "originX":"left",
            "originY":"top",
            "left":797.99,
            "top":329,
            "width":48.02,
            "height":3,
            "fill":null,
            "stroke":"black",
            "strokeWidth":10,
            "strokeDashArray":null,
            "strokeLineCap":"round",
            "strokeLineJoin":"round",
            "strokeMiterLimit":10,
            "scaleX":1,
            "scaleY":1,
            "angle":0,
            "flipX":false,
            "flipY":false,
            "opacity":1,
            "shadow":null,
            "visible":true,
            "clipTo":null,
            "backgroundColor":"",
            "fillRule":"nonzero",
            "globalCompositeOperation":"source-over",
            "transformMatrix":null,
            "skewX":0,
            "skewY":0,
            "pathOffset":{
                "x":827,
                "y":335.5
            },
            "path":[
                [
                    "M",
                    851.01,
                    334
                ],
                [
                    "Q",
                    851,
                    334,
                    850.5,
                    334
                ],
                [
                    "Q",
                    850,
                    334,
                    849.5,
                    334
                ],
                [
                    "Q",
                    849,
                    334,
                    848,
                    334
                ],
                [
                    "Q",
                    847,
                    334,
                    846.5,
                    334
                ],
                [
                    "Q",
                    846,
                    334,
                    845,
                    334
                ],
                [
                    "Q",
                    844,
                    334,
                    843.5,
                    334
                ],
                [
                    "Q",
                    843,
                    334,
                    842,
                    334
                ],
                [
                    "Q",
                    841,
                    334,
                    840.5,
                    334
                ],
                [
                    "Q",
                    840,
                    334,
                    839,
                    334
                ],
                [
                    "Q",
                    838,
                    334,
                    837,
                    334
                ],
                [
                    "Q",
                    836,
                    334,
                    834.5,
                    334
                ],
                [
                    "Q",
                    833,
                    334,
                    831.5,
                    334
                ],
                [
                    "Q",
                    830,
                    334,
                    828,
                    334
                ],
                [
                    "Q",
                    826,
                    334,
                    824.5,
                    334
                ],
                [
                    "Q",
                    823,
                    334,
                    821.5,
                    334
                ],
                [
                    "Q",
                    820,
                    334,
                    819,
                    334.5
                ],
                [
                    "Q",
                    818,
                    335,
                    816.5,
                    335
                ],
                [
                    "Q",
                    815,
                    335,
                    814,
                    335.5
                ],
                [
                    "Q",
                    813,
                    336,
                    811.5,
                    336
                ],
                [
                    "Q",
                    810,
                    336,
                    809.5,
                    336
                ],
                [
                    "Q",
                    809,
                    336,
                    808.5,
                    336.5
                ],
                [
                    "Q",
                    808,
                    337,
                    807.5,
                    337
                ],
                [
                    "Q",
                    807,
                    337,
                    806.5,
                    337
                ],
                [
                    "Q",
                    806,
                    337,
                    805.5,
                    337
                ],
                [
                    "Q",
                    805,
                    337,
                    804.5,
                    337
                ],
                [
                    "Q",
                    804,
                    337,
                    803.5,
                    337
                ],
                [
                    "L",
                    802.99,
                    337
                ]
            ]
        },
        {
            "type":"path",
            "originX":"left",
            "originY":"top",
            "left":884,
            "top":296,
            "width":77.01,
            "height":66,
            "fill":null,
            "stroke":"black",
            "strokeWidth":10,
            "strokeDashArray":null,
            "strokeLineCap":"round",
            "strokeLineJoin":"round",
            "strokeMiterLimit":10,
            "scaleX":1,
            "scaleY":1,
            "angle":0,
            "flipX":false,
            "flipY":false,
            "opacity":1,
            "shadow":null,
            "visible":true,
            "clipTo":null,
            "backgroundColor":"",
            "fillRule":"nonzero",
            "globalCompositeOperation":"source-over",
            "transformMatrix":null,
            "skewX":0,
            "skewY":0,
            "pathOffset":{
                "x":927.505,
                "y":334
            },
            "path":[
                [
                    "M",
                    966.01,
                    301
                ],
                [
                    "Q",
                    966,
                    301,
                    965.5,
                    301
                ],
                [
                    "Q",
                    965,
                    301,
                    964,
                    301
                ],
                [
                    "Q",
                    963,
                    301,
                    962.5,
                    301
                ],
                [
                    "Q",
                    962,
                    301,
                    959.5,
                    301
                ],
                [
                    "Q",
                    957,
                    301,
                    955,
                    301
                ],
                [
                    "Q",
                    953,
                    301,
                    949.5,
                    301
                ],
                [
                    "Q",
                    946,
                    301,
                    943,
                    301
                ],
                [
                    "Q",
                    940,
                    301,
                    937,
                    301
                ],
                [
                    "Q",
                    934,
                    301,
                    930,
                    301
                ],
                [
                    "Q",
                    926,
                    301,
                    922,
                    301
                ],
                [
                    "Q",
                    918,
                    301,
                    914.5,
                    301
                ],
                [
                    "Q",
                    911,
                    301,
                    908,
                    301
                ],
                [
                    "Q",
                    905,
                    301,
                    902,
                    301.5
                ],
                [
                    "Q",
                    899,
                    302,
                    897,
                    302
                ],
                [
                    "Q",
                    895,
                    302,
                    893.5,
                    302.5
                ],
                [
                    "Q",
                    892,
                    303,
                    891.5,
                    303.5
                ],
                [
                    "Q",
                    891,
                    304,
                    890.5,
                    304.5
                ],
                [
                    "Q",
                    890,
                    305,
                    889.5,
                    305.5
                ],
                [
                    "Q",
                    889,
                    306,
                    889,
                    307
                ],
                [
                    "Q",
                    889,
                    308,
                    889,
                    308.5
                ],
                [
                    "Q",
                    889,
                    309,
                    889,
                    309.5
                ],
                [
                    "Q",
                    889,
                    310,
                    889,
                    310.5
                ],
                [
                    "Q",
                    889,
                    311,
                    889,
                    311.5
                ],
                [
                    "Q",
                    889,
                    312,
                    890,
                    313
                ],
                [
                    "Q",
                    891,
                    314,
                    891.5,
                    315
                ],
                [
                    "Q",
                    892,
                    316,
                    893,
                    317.5
                ],
                [
                    "Q",
                    894,
                    319,
                    894.5,
                    320
                ],
                [
                    "Q",
                    895,
                    321,
                    895.5,
                    322
                ],
                [
                    "Q",
                    896,
                    323,
                    896.5,
                    323.5
                ],
                [
                    "Q",
                    897,
                    324,
                    897.5,
                    324
                ],
                [
                    "Q",
                    898,
                    324,
                    898.5,
                    325
                ],
                [
                    "Q",
                    899,
                    326,
                    900,
                    326
                ],
                [
                    "Q",
                    901,
                    326,
                    902.5,
                    327
                ],
                [
                    "Q",
                    904,
                    328,
                    905.5,
                    329
                ],
                [
                    "Q",
                    907,
                    330,
                    909,
                    331.5
                ],
                [
                    "Q",
                    911,
                    333,
                    912.5,
                    334
                ],
                [
                    "Q",
                    914,
                    335,
                    915.5,
                    336
                ],
                [
                    "Q",
                    917,
                    337,
                    918.5,
                    338
                ],
                [
                    "Q",
                    920,
                    339,
                    921,
                    340
                ],
                [
                    "Q",
                    922,
                    341,
                    923,
                    342
                ],
                [
                    "Q",
                    924,
                    343,
                    925,
                    344
                ],
                [
                    "Q",
                    926,
                    345,
                    927.5,
                    347
                ],
                [
                    "Q",
                    929,
                    349,
                    929,
                    349.5
                ],
                [
                    "Q",
                    929,
                    350,
                    930.5,
                    352
                ],
                [
                    "Q",
                    932,
                    354,
                    932.5,
                    355
                ],
                [
                    "Q",
                    933,
                    356,
                    933.5,
                    357
                ],
                [
                    "Q",
                    934,
                    358,
                    934.5,
                    359
                ],
                [
                    "Q",
                    935,
                    360,
                    935.5,
                    360.5
                ],
                [
                    "Q",
                    936,
                    361,
                    936,
                    362
                ],
                [
                    "Q",
                    936,
                    363,
                    936.5,
                    363
                ],
                [
                    "Q",
                    937,
                    363,
                    937,
                    363.5
                ],
                [
                    "Q",
                    937,
                    364,
                    937,
                    364.5
                ],
                [
                    "Q",
                    937,
                    365,
                    937,
                    365.5
                ],
                [
                    "Q",
                    937,
                    366,
                    937,
                    366.5
                ],
                [
                    "Q",
                    937,
                    367,
                    936.5,
                    367
                ],
                [
                    "Q",
                    936,
                    367,
                    935.5,
                    367
                ],
                [
                    "Q",
                    935,
                    367,
                    934.5,
                    367
                ],
                [
                    "Q",
                    934,
                    367,
                    933.5,
                    367
                ],
                [
                    "Q",
                    933,
                    367,
                    932,
                    367
                ],
                [
                    "Q",
                    931,
                    367,
                    929.5,
                    367
                ],
                [
                    "Q",
                    928,
                    367,
                    927,
                    367
                ],
                [
                    "Q",
                    926,
                    367,
                    924,
                    367
                ],
                [
                    "Q",
                    922,
                    367,
                    920.5,
                    367
                ],
                [
                    "Q",
                    919,
                    367,
                    917.5,
                    367
                ],
                [
                    "Q",
                    916,
                    367,
                    914.5,
                    367
                ],
                [
                    "Q",
                    913,
                    367,
                    911.5,
                    366.5
                ],
                [
                    "Q",
                    910,
                    366,
                    909,
                    366
                ],
                [
                    "Q",
                    908,
                    366,
                    907,
                    366
                ],
                [
                    "Q",
                    906,
                    366,
                    905,
                    366
                ],
                [
                    "Q",
                    904,
                    366,
                    903,
                    366
                ],
                [
                    "Q",
                    902,
                    366,
                    901.5,
                    365.5
                ],
                [
                    "Q",
                    901,
                    365,
                    900.5,
                    365
                ],
                [
                    "Q",
                    900,
                    365,
                    899.5,
                    365
                ],
                [
                    "Q",
                    899,
                    365,
                    898.5,
                    365
                ],
                [
                    "Q",
                    898,
                    365,
                    897.5,
                    364.5
                ],
                [
                    "Q",
                    897,
                    364,
                    896.5,
                    364
                ],
                [
                    "Q",
                    896,
                    364,
                    895.5,
                    364
                ],
                [
                    "Q",
                    895,
                    364,
                    895,
                    363.5
                ],
                [
                    "Q",
                    895,
                    363,
                    894.5,
                    363
                ],
                [
                    "L",
                    893.99,
                    363
                ]
            ]
        }
    ]
}